model: 'densenet40'
concat:
    - - 'conv1.weight'
      - 'dense1.0.bn1.weight'
      - 'dense1.0.conv1.weight'
      - 'dense1.1.bn1.weight'
      - 'dense1.1.conv1.weight'
      - 'dense1.2.bn1.weight'
      - 'dense1.2.conv1.weight'
      - 'dense1.3.bn1.weight'
      - 'dense1.3.conv1.weight'
      - 'dense1.4.bn1.weight'
      - 'dense1.4.conv1.weight'
      - 'dense1.5.bn1.weight'
      - 'dense1.5.conv1.weight'
      - 'dense1.6.bn1.weight'
      - 'dense1.6.conv1.weight'
      - 'dense1.7.bn1.weight'
      - 'dense1.7.conv1.weight'
      - 'dense1.8.bn1.weight'
      - 'dense1.8.conv1.weight'
      - 'dense1.9.bn1.weight'
      - 'dense1.9.conv1.weight'
      - 'dense1.10.bn1.weight'
      - 'dense1.10.conv1.weight'
      - 'dense1.11.bn1.weight'
      - 'dense1.11.conv1.weight'
      - 'trans1.bn1.weight'

    - - 'trans1.conv1.weight'
      - 'dense2.0.bn1.weight'
      - 'dense2.0.conv1.weight'
      - 'dense2.1.bn1.weight'
      - 'dense2.1.conv1.weight'
      - 'dense2.2.bn1.weight'
      - 'dense2.2.conv1.weight'
      - 'dense2.3.bn1.weight'
      - 'dense2.3.conv1.weight'
      - 'dense2.4.bn1.weight'
      - 'dense2.4.conv1.weight'
      - 'dense2.5.bn1.weight'
      - 'dense2.5.conv1.weight'
      - 'dense2.6.bn1.weight'
      - 'dense2.6.conv1.weight'
      - 'dense2.7.bn1.weight'
      - 'dense2.7.conv1.weight'
      - 'dense2.8.bn1.weight'
      - 'dense2.8.conv1.weight'
      - 'dense2.9.bn1.weight'
      - 'dense2.9.conv1.weight'
      - 'dense2.10.bn1.weight'
      - 'dense2.10.conv1.weight'
      - 'dense2.11.bn1.weight'
      - 'dense2.11.conv1.weight'
      - 'trans2.bn1.weight'

    - - 'trans2.conv1.weight'
      - 'dense3.0.bn1.weight'
      - 'dense3.0.conv1.weight'
      - 'dense3.1.bn1.weight'
      - 'dense3.1.conv1.weight'
      - 'dense3.2.bn1.weight'
      - 'dense3.2.conv1.weight'
      - 'dense3.3.bn1.weight'
      - 'dense3.3.conv1.weight'
      - 'dense3.4.bn1.weight'
      - 'dense3.4.conv1.weight'
      - 'dense3.5.bn1.weight'
      - 'dense3.5.conv1.weight'
      - 'dense3.6.bn1.weight'
      - 'dense3.6.conv1.weight'
      - 'dense3.7.bn1.weight'
      - 'dense3.7.conv1.weight'
      - 'dense3.8.bn1.weight'
      - 'dense3.8.conv1.weight'
      - 'dense3.9.bn1.weight'
      - 'dense3.9.conv1.weight'
      - 'dense3.10.bn1.weight'
      - 'dense3.10.conv1.weight'
      - 'dense3.11.bn1.weight'
      - 'dense3.11.conv1.weight'
      - 'bn.weight'
groups:
downsample:
stage: