model: 'googlenet'
concat:
  - - 'pre_layers.0.weight'
  - - 'inception_a3.branch1x1.0.weight'
    - 'inception_a3.branch3x3.0.weight'
    - 'inception_a3.branch5x5.0.weight'
    - 'inception_a3.branch_pool.1.weight'
  - - 'inception_b3.branch1x1.0.weight'
    - 'inception_b3.branch3x3.0.weight'
    - 'inception_b3.branch5x5.0.weight'
    - 'inception_b3.branch_pool.1.weight'
  - - 'inception_a4.branch1x1.0.weight'
    - 'inception_a4.branch3x3.0.weight'
    - 'inception_a4.branch5x5.0.weight'
    - 'inception_a4.branch_pool.1.weight'
  - - 'inception_b4.branch1x1.0.weight'
    - 'inception_b4.branch3x3.0.weight'
    - 'inception_b4.branch5x5.0.weight'
    - 'inception_b4.branch_pool.1.weight'
  - - 'inception_c4.branch1x1.0.weight'
    - 'inception_c4.branch3x3.0.weight'
    - 'inception_c4.branch5x5.0.weight'
    - 'inception_c4.branch_pool.1.weight'
  - - 'inception_d4.branch1x1.0.weight'
    - 'inception_d4.branch3x3.0.weight'
    - 'inception_d4.branch5x5.0.weight'
    - 'inception_d4.branch_pool.1.weight'
  - - 'inception_e4.branch1x1.0.weight'
    - 'inception_e4.branch3x3.0.weight'
    - 'inception_e4.branch5x5.0.weight'
    - 'inception_e4.branch_pool.1.weight'
  - - 'inception_a5.branch1x1.0.weight'
    - 'inception_a5.branch3x3.0.weight'
    - 'inception_a5.branch5x5.0.weight'
    - 'inception_a5.branch_pool.1.weight'
  - - 'inception_b5.branch1x1.0.weight'
    - 'inception_b5.branch3x3.0.weight'
    - 'inception_b5.branch5x5.0.weight'
    - 'inception_b5.branch_pool.1.weight'
  - - 'linear.weight'
groups:
downsample:
stage: